name: detect runtime error

on:
    schedule:
        - cron: "0 22 * * *"
jobs:
    detectError:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repository
              uses: actions/checkout@v2
            - name: create config variable
              run: |
                  node createConfigVariable.js
            - name: set global error variable
              run: |
                  echo "ERROR_VARIABLE=$(head -n 1 ./errorVariable.txt)" >> $GITHUB_ENV
            - name: set url
              run: |
                  echo "URLS=$(head -n 1 ./url.txt)" >> $GITHUB_ENV
            - name: detect runtime error
              uses: nhn/toast-ui.detect-runtime-error-actions@v1.0.1
              with:
                  global-error-log-variable: ${{ env.ERROR_VARIABLE }}
                  urls: ${{ env.URLS }}
                  browserlist: ie9, ie10, ie11, safari, edge, firefox, chrome
              env:
                  BROWSERSTACK_USERNAME: ${{secrets.BROWSERSTACK_USERNAME}}
                  BROWSERSTACK_ACCESS_KEY: ${{secrets.BROWSERSTACK_ACCESS_KEY}}
